import type { FileTreeNode, IterationNode, AgentEvent } from "@vibe-studio/shared";
import type { SelectedFile } from "./types";

// --- Mock file tree ---
export const MOCK_FILE_TREE: FileTreeNode[] = [
  {
    name: "src",
    path: "src",
    type: "directory",
    children: [
      {
        name: "app",
        path: "src/app",
        type: "directory",
        children: [
          { name: "layout.tsx", path: "src/app/layout.tsx", type: "file" },
          { name: "page.tsx", path: "src/app/page.tsx", type: "file", status: "modified" },
          {
            name: "dashboard",
            path: "src/app/dashboard",
            type: "directory",
            children: [
              { name: "page.tsx", path: "src/app/dashboard/page.tsx", type: "file", status: "added" },
              { name: "layout.tsx", path: "src/app/dashboard/layout.tsx", type: "file", status: "added" },
            ],
          },
        ],
      },
      {
        name: "components",
        path: "src/components",
        type: "directory",
        children: [
          { name: "Header.tsx", path: "src/components/Header.tsx", type: "file", status: "added" },
          { name: "Sidebar.tsx", path: "src/components/Sidebar.tsx", type: "file", status: "added" },
          { name: "StatsCard.tsx", path: "src/components/StatsCard.tsx", type: "file", status: "added" },
          { name: "DataTable.tsx", path: "src/components/DataTable.tsx", type: "file", status: "added" },
        ],
      },
      {
        name: "lib",
        path: "src/lib",
        type: "directory",
        children: [
          { name: "utils.ts", path: "src/lib/utils.ts", type: "file" },
        ],
      },
    ],
  },
  { name: "tailwind.config.ts", path: "tailwind.config.ts", type: "file" },
  { name: "next.config.js", path: "next.config.js", type: "file" },
  { name: "package.json", path: "package.json", type: "file" },
];

// --- Mock file contents ---
export const MOCK_FILE_CONTENTS: Record<string, SelectedFile> = {
  "src/app/layout.tsx": {
    path: "src/app/layout.tsx",
    name: "layout.tsx",
    language: "tsx",
    content: `import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by Vibe Studio",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}`,
  },
  "src/app/page.tsx": {
    path: "src/app/page.tsx",
    name: "page.tsx",
    language: "tsx",
    content: `import { Header } from "@/components/Header";
import { StatsCard } from "@/components/StatsCard";

export default function Home() {
  return (
    <main className="min-h-screen bg-background">
      <Header />
      <div className="container mx-auto px-6 py-8">
        <h1 className="text-3xl font-bold mb-6">Dashboard</h1>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <StatsCard title="Revenue" value="$45,231" change={+12.5} />
          <StatsCard title="Users" value="2,350" change={+8.1} />
          <StatsCard title="Orders" value="1,247" change={-3.2} />
        </div>
      </div>
    </main>
  );
}`,
  },
  "src/app/dashboard/page.tsx": {
    path: "src/app/dashboard/page.tsx",
    name: "page.tsx",
    language: "tsx",
    content: `import { DataTable } from "@/components/DataTable";

export default function DashboardPage() {
  return (
    <div className="p-6">
      <h2 className="text-2xl font-semibold mb-4">Recent Activity</h2>
      <DataTable />
    </div>
  );
}`,
  },
  "src/app/dashboard/layout.tsx": {
    path: "src/app/dashboard/layout.tsx",
    name: "layout.tsx",
    language: "tsx",
    content: `import { Sidebar } from "@/components/Sidebar";

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex h-screen">
      <Sidebar />
      <main className="flex-1 overflow-auto">{children}</main>
    </div>
  );
}`,
  },
  "src/components/Header.tsx": {
    path: "src/components/Header.tsx",
    name: "Header.tsx",
    language: "tsx",
    content: `export function Header() {
  return (
    <header
      data-figma-node-id="header-01"
      className="border-b bg-white px-6 py-4 flex items-center justify-between"
    >
      <div className="flex items-center gap-2">
        <span className="text-xl font-bold">Acme Inc</span>
      </div>
      <nav className="flex items-center gap-4">
        <a href="/" className="text-sm text-muted-foreground hover:text-foreground">
          Home
        </a>
        <a href="/dashboard" className="text-sm text-muted-foreground hover:text-foreground">
          Dashboard
        </a>
      </nav>
    </header>
  );
}`,
  },
  "src/components/Sidebar.tsx": {
    path: "src/components/Sidebar.tsx",
    name: "Sidebar.tsx",
    language: "tsx",
    content: `export function Sidebar() {
  return (
    <aside
      data-figma-node-id="sidebar-01"
      className="w-64 border-r bg-muted/40 p-4"
    >
      <nav className="space-y-2">
        <a href="/dashboard" className="block rounded-md px-3 py-2 text-sm font-medium bg-accent">
          Overview
        </a>
        <a href="/dashboard/analytics" className="block rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-accent">
          Analytics
        </a>
        <a href="/dashboard/settings" className="block rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-accent">
          Settings
        </a>
      </nav>
    </aside>
  );
}`,
  },
  "src/components/StatsCard.tsx": {
    path: "src/components/StatsCard.tsx",
    name: "StatsCard.tsx",
    language: "tsx",
    content: `interface StatsCardProps {
  title: string;
  value: string;
  change: number;
}

export function StatsCard({ title, value, change }: StatsCardProps) {
  return (
    <div
      data-figma-node-id="stats-card-01"
      className="rounded-lg border bg-card p-6 shadow-sm"
    >
      <p className="text-sm text-muted-foreground">{title}</p>
      <p className="text-2xl font-bold mt-1">{value}</p>
      <p className={\`text-sm mt-2 \${change >= 0 ? "text-green-600" : "text-red-600"}\`}>
        {change >= 0 ? "+" : ""}{change}%
      </p>
    </div>
  );
}`,
  },
  "src/components/DataTable.tsx": {
    path: "src/components/DataTable.tsx",
    name: "DataTable.tsx",
    language: "tsx",
    content: `const rows = [
  { id: 1, name: "John Doe", email: "john@example.com", status: "Active" },
  { id: 2, name: "Jane Smith", email: "jane@example.com", status: "Pending" },
  { id: 3, name: "Bob Wilson", email: "bob@example.com", status: "Active" },
];

export function DataTable() {
  return (
    <div data-figma-node-id="data-table-01" className="rounded-lg border">
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b bg-muted/50">
            <th className="px-4 py-3 text-left font-medium">Name</th>
            <th className="px-4 py-3 text-left font-medium">Email</th>
            <th className="px-4 py-3 text-left font-medium">Status</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr key={row.id} className="border-b">
              <td className="px-4 py-3">{row.name}</td>
              <td className="px-4 py-3 text-muted-foreground">{row.email}</td>
              <td className="px-4 py-3">{row.status}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}`,
  },
  "src/lib/utils.ts": {
    path: "src/lib/utils.ts",
    name: "utils.ts",
    language: "typescript",
    content: `import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}`,
  },
  "tailwind.config.ts": {
    path: "tailwind.config.ts",
    name: "tailwind.config.ts",
    language: "typescript",
    content: `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: { extend: {} },
  plugins: [],
};

export default config;`,
  },
  "package.json": {
    path: "package.json",
    name: "package.json",
    language: "json",
    content: `{
  "name": "generated-dashboard",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^14.2.0",
    "react": "^18.3.0",
    "react-dom": "^18.3.0"
  }
}`,
  },
};

// --- Mock trace tree ---
export const MOCK_TRACE_TREE: IterationNode = {
  nodeId: "root",
  iterationIndex: 0,
  stepKey: "vibeLoop",
  title: "Vibe Loop — Dashboard App",
  status: "running",
  startedAt: "2026-02-20T10:00:00.000Z",
  children: [
    {
      nodeId: "step-import",
      parentNodeId: "root",
      iterationIndex: 0,
      stepKey: "importDesignPack",
      title: "Import Design Pack",
      status: "success",
      startedAt: "2026-02-20T10:00:00.000Z",
      finishedAt: "2026-02-20T10:00:02.300Z",
      message: "Validated manifest.json and design-ir.json",
      artifacts: [
        {
          id: "art-1",
          kind: "designPack",
          label: "design-pack.zip",
          href: "/api/projects/demo/artifacts/design-pack.zip",
          mime: "application/zip",
          sizeBytes: 245760,
        },
        {
          id: "art-2",
          kind: "designIr",
          label: "design-ir.json",
          href: "/api/projects/demo/artifacts/design-ir.json",
          mime: "application/json",
        },
      ],
    },
    {
      nodeId: "step-generate",
      parentNodeId: "root",
      iterationIndex: 0,
      stepKey: "generate",
      title: "Generate Initial Code",
      status: "success",
      startedAt: "2026-02-20T10:00:02.300Z",
      finishedAt: "2026-02-20T10:00:08.100Z",
      message: "Generated 7 files from Design IR",
      artifacts: [
        {
          id: "art-3",
          kind: "workspaceFile",
          label: "src/app/page.tsx",
          href: "/api/projects/demo/file?path=src/app/page.tsx",
          mime: "text/plain",
        },
      ],
    },
    {
      nodeId: "iter-1",
      parentNodeId: "root",
      iterationIndex: 1,
      stepKey: "iteration",
      title: "Iteration 1",
      status: "success",
      startedAt: "2026-02-20T10:00:08.100Z",
      finishedAt: "2026-02-20T10:00:18.500Z",
      score: {
        overall: 0.72,
        layout: 0.68,
        style: 0.75,
        a11y: 0.80,
        deltaFromPrev: 0.72,
      },
      children: [
        {
          nodeId: "iter-1-evaluate",
          parentNodeId: "iter-1",
          iterationIndex: 1,
          stepKey: "evaluate",
          title: "Playwright Snapshot",
          status: "success",
          startedAt: "2026-02-20T10:00:08.100Z",
          finishedAt: "2026-02-20T10:00:11.200Z",
          message: "Captured snapshot at 1440x900",
          artifacts: [
            {
              id: "art-4",
              kind: "snapshotJson",
              label: "snapshot-iter1.json",
              href: "/api/projects/demo/artifacts/snapshots/iter-1.json",
              mime: "application/json",
            },
          ],
        },
        {
          nodeId: "iter-1-score",
          parentNodeId: "iter-1",
          iterationIndex: 1,
          stepKey: "score",
          title: "Score: 0.72",
          status: "success",
          startedAt: "2026-02-20T10:00:11.200Z",
          finishedAt: "2026-02-20T10:00:12.800Z",
          score: { overall: 0.72, layout: 0.68, style: 0.75, a11y: 0.80 },
          artifacts: [
            {
              id: "art-5",
              kind: "scoreReportJson",
              label: "score-iter1.json",
              href: "/api/projects/demo/artifacts/reports/iter-1.json",
              mime: "application/json",
            },
          ],
        },
        {
          nodeId: "iter-1-patch",
          parentNodeId: "iter-1",
          iterationIndex: 1,
          stepKey: "patch",
          title: "Apply Patch",
          status: "success",
          startedAt: "2026-02-20T10:00:12.800Z",
          finishedAt: "2026-02-20T10:00:18.500Z",
          message: "Patched 3 files (layout fixes)",
          artifacts: [
            {
              id: "art-6",
              kind: "diffPatch",
              label: "patch-iter1.diff",
              href: "/api/projects/demo/artifacts/patches/iter-1.diff",
              mime: "text/plain",
            },
          ],
        },
      ],
    },
    {
      nodeId: "iter-2",
      parentNodeId: "root",
      iterationIndex: 2,
      stepKey: "iteration",
      title: "Iteration 2",
      status: "running",
      startedAt: "2026-02-20T10:00:18.500Z",
      score: {
        overall: 0.85,
        layout: 0.83,
        style: 0.88,
        a11y: 0.82,
        deltaFromPrev: 0.13,
      },
      children: [
        {
          nodeId: "iter-2-evaluate",
          parentNodeId: "iter-2",
          iterationIndex: 2,
          stepKey: "evaluate",
          title: "Playwright Snapshot",
          status: "success",
          startedAt: "2026-02-20T10:00:18.500Z",
          finishedAt: "2026-02-20T10:00:21.000Z",
          message: "Captured snapshot at 1440x900",
        },
        {
          nodeId: "iter-2-score",
          parentNodeId: "iter-2",
          iterationIndex: 2,
          stepKey: "score",
          title: "Score: 0.85",
          status: "success",
          startedAt: "2026-02-20T10:00:21.000Z",
          finishedAt: "2026-02-20T10:00:22.100Z",
          score: { overall: 0.85, layout: 0.83, style: 0.88, a11y: 0.82, deltaFromPrev: 0.13 },
        },
        {
          nodeId: "iter-2-patch",
          parentNodeId: "iter-2",
          iterationIndex: 2,
          stepKey: "patch",
          title: "Apply Patch",
          status: "running",
          startedAt: "2026-02-20T10:00:22.100Z",
          message: "Patching style mismatches...",
        },
      ],
    },
    {
      nodeId: "iter-3",
      parentNodeId: "root",
      iterationIndex: 3,
      stepKey: "iteration",
      title: "Iteration 3",
      status: "queued",
    },
  ],
};

// --- Mock event stream for simulated WS ---
export function createMockEventStream(): AgentEvent[] {
  const now = Date.now();
  return [
    {
      eventId: "evt-1",
      projectId: "demo",
      nodeId: "iter-2-patch",
      type: "nodeProgress",
      ts: new Date(now + 1000).toISOString(),
      payload: {
        status: "running",
        message: "Applying style fixes to Header.tsx...",
        progressPct: 40,
      },
    },
    {
      eventId: "evt-2",
      projectId: "demo",
      nodeId: "iter-2-patch",
      type: "nodeProgress",
      ts: new Date(now + 3000).toISOString(),
      payload: {
        status: "running",
        message: "Applying layout fixes to StatsCard.tsx...",
        progressPct: 75,
      },
    },
    {
      eventId: "evt-3",
      projectId: "demo",
      nodeId: "iter-2-patch",
      type: "nodeFinished",
      ts: new Date(now + 5000).toISOString(),
      payload: {
        status: "success",
        message: "Patched 2 files (style fixes)",
      },
    },
    {
      eventId: "evt-4",
      projectId: "demo",
      nodeId: "iter-2",
      type: "nodeFinished",
      ts: new Date(now + 5500).toISOString(),
      payload: {
        status: "success",
        score: { overall: 0.85, layout: 0.83, style: 0.88, a11y: 0.82, deltaFromPrev: 0.13 },
      },
    },
    {
      eventId: "evt-5",
      projectId: "demo",
      nodeId: "iter-3",
      type: "nodeStarted",
      ts: new Date(now + 6000).toISOString(),
      payload: {
        stepKey: "iteration",
        title: "Iteration 3",
        status: "running",
      },
    },
    {
      eventId: "evt-6",
      projectId: "demo",
      nodeId: "iter-3-evaluate",
      type: "nodeCreated",
      ts: new Date(now + 6500).toISOString(),
      payload: {
        stepKey: "evaluate",
        title: "Playwright Snapshot",
        status: "running",
      },
    },
    {
      eventId: "evt-7",
      projectId: "demo",
      nodeId: "iter-3-evaluate",
      type: "nodeFinished",
      ts: new Date(now + 9000).toISOString(),
      payload: {
        status: "success",
        message: "Captured snapshot at 1440x900",
      },
    },
    {
      eventId: "evt-8",
      projectId: "demo",
      nodeId: "iter-3-score",
      type: "nodeCreated",
      ts: new Date(now + 9500).toISOString(),
      payload: {
        stepKey: "score",
        title: "Score: 0.93",
        status: "running",
      },
    },
    {
      eventId: "evt-9",
      projectId: "demo",
      nodeId: "iter-3-score",
      type: "nodeFinished",
      ts: new Date(now + 11000).toISOString(),
      payload: {
        status: "success",
        score: { overall: 0.93, layout: 0.91, style: 0.95, a11y: 0.90, deltaFromPrev: 0.08 },
      },
    },
    {
      eventId: "evt-10",
      projectId: "demo",
      nodeId: "iter-3",
      type: "nodeFinished",
      ts: new Date(now + 11500).toISOString(),
      payload: {
        status: "success",
        message: "Threshold 0.92 met! Score: 0.93",
        score: { overall: 0.93, layout: 0.91, style: 0.95, a11y: 0.90 },
      },
    },
    {
      eventId: "evt-11",
      projectId: "demo",
      nodeId: "root",
      type: "nodeFinished",
      ts: new Date(now + 12000).toISOString(),
      payload: {
        status: "success",
        message: "Vibe loop complete — 3 iterations, final score: 0.93",
        score: { overall: 0.93 },
      },
    },
  ];
}
